export const SALESFORCE_OBJECTS = {
  ACCOUNT: 'Account',
  CONTACT: 'Contact',
  PRODUCT: 'Product2',
  PRICEBOOK_ENTRY: 'PricebookEntry',
  PRICEBOOK: 'Pricebook2',
  ORDER: 'Order',
  ORDER_ITEM: 'OrderItem',
  RETURN_ORDER: 'ReturnOrder',
  RETURN_ORDER_LINE_ITEM: 'ReturnOrderLineItem',
  INVOICE: 'Invoice',
  INVOICE_LINE: 'InvoiceLine',
  CLAIM: 'Claim',
  CLAIM_ITEM: 'ClaimItem',
  PARTNER_FUND_CLAIM: 'PartnerFundClaim',
  FULFILLMENT_ORDER: 'FulfillmentOrder',
  ORDER_SUMMARY: 'OrderSummary',
  CREDIT_MEMO: 'CreditMemo',
} as const;

export const SALESFORCE_CUSTOM_OBJECTS = {
  SFA_USER: 'SFA_User__c',
  PURCHASE_ORDER: 'Order',
  PURCHASE_ORDER_ITEM: 'Purchase_Order_Item__c',
  RETURN_ORDER_CUSTOM: 'Return_Order__c',
  RETURN_ORDER_LINE_ITEM_CUSTOM: 'Return_Order_Line_Item__c',
  INVOICE_CUSTOM: 'Invoice__c',
  INVOICE_LINE_ITEM_CUSTOM: 'Invoice_Line_Item__c',
  CLAIM_CUSTOM: 'Claim__c',
  BULK_CLAIM: 'BulkClaim__c',
  GRN: 'Goods_Receipt__c',
  GRN_LINE: 'GRN_Line__c',
  DISPATCH_REQUEST: 'Dispatch_Request__c',
  INVENTORY_BATCH: 'Inventory_Batch__c',
  STORE_SCHEME: 'StoreScheme__c',
  SCHEME_SLAB_TARGET: 'Scheme_Slab_Target__c',
  PRODUCT_FLAG: 'Product_Flag__c',
  COMPETING_PRODUCT: 'Competing_Product__c',
  SFA_PERFORMANCE: 'SFA_Performance__c',
  DISTRIBUTOR_MANAGER_MEETING: 'Distributor_Manager_Meeting__c',
  DISTRIBUTOR_FRAUD_ANALYTICS: 'Distributor_Fraud_Analytics__c',
  CREDIT_NOTE: 'Credit_Note__c',
  CREDIT_NOTE_USAGE: 'Credit_Note_Usage__c',
  ORDER_WITH_PROMOTION: 'OrderWithPromotion__c',
  REPLENISHMENT_SETTINGS: 'Replenishment_Settings__mdt',
  PRICING_DISCUSSION: 'Pricing_Discussion__c',
} as const;

export const SALESFORCE_FIELD_MAP = {
  ACCOUNT: {
    ID: 'Id',
    NAME: 'Name',
    TYPE: 'Type',
    IS_PARTNER: 'IsPartner',
    EMAIL: 'Email__c',
    DISTRIBUTOR_PARENT: 'Distributor__c',
    BUSINESS_TYPE: 'Business_Type__c',
    TRANSPORT_FACILITY: 'Transport_Facility_Type__c',
  },
  CONTACT: {
    ID: 'Id',
    EMAIL: 'Email',
    FIRST_NAME: 'FirstName',
    LAST_NAME: 'LastName',
    DISTRIBUTOR: 'Distributor__c',
    ACCOUNT_ID: 'AccountId',
  },
  SFA_USER: {
    ID: 'Id',
    NAME: 'Name__c',
    EMAIL: 'email__c',
    PASSWORD: 'password__c',
    IS_ACTIVE: 'IsActive__c',
    OTP_CODE: 'OTP_Code__c',
  },
  PURCHASE_ORDER: {
    ID: 'Id',
    NAME: 'OrderNumber',
    DISTRIBUTOR: 'AccountId',
    STATUS: 'Status',
    TOTAL_AMOUNT: 'Total_Amount__c',
    SCHEME_DISCOUNT: 'Discount_Amount__c',
    DISCOUNT_AMOUNT: 'Discount_Amount__c',
    TAX_AMOUNT: 'Tax_Amount__c',
    GRAND_TOTAL: 'Grand_Total__c',
    ORDER_DATE: 'EffectiveDate',
    SUPPLIER: 'Distributor_Account__c',
    SFA_USER: 'SFA_User__c',
    APPLIED_SCHEME: 'Applied_scheme__c',
    SCHEME_TYPE: 'Scheme_type__c',
    SCHEME_APPLIED: 'SchemeApplied__c',
    NOTES: 'Description',
    APPROVAL_STATUS: 'Approval_Status__c',
    CURRENCY: 'Currency__c',
    PAYMENT_TERMS: 'Payment_Terms__c',
    DELIVERY_TERMS: 'Delivery_Terms__c',
    REFERENCE_NUMBER: 'Reference_Number__c',
  },
  PURCHASE_ORDER_ITEM: {
    ID: 'Id',
    ORDER: 'Order__c',
    PRODUCT: 'Product__c',
    QUANTITY: 'Quantity__c',
    GOOD_QUANTITY: 'Good_Quantity__c',
    DEFECTIVE_QUANTITY: 'Defective_product_Quantity__c',
    STATUS: 'Status__c',
    UNIT_OF_MEASURE: 'Unit_Of_Measure__c',
    PRODUCT_CONDITION: 'Product_Condition__c',
  },
  RETURN_ORDER_CUSTOM: {
    ID: 'Id',
    NAME: 'Name',
    ACCOUNT: 'Account__c',
    ORDER: 'Order__c',
    STATUS: 'Status__c',
    GRAND_TOTAL: 'Grand_Total__c',
    REVERSE_SCHEME_AMOUNT: 'Reverse_Scheme_Amount__c',
    FINAL_AMOUNT: 'Final_Amount__c',
    GRN: 'Goods_Receipt_Note__c',
    INVOICE: 'Invoice_Custom__c',
    CASE: 'Case__c',
    DESCRIPTION: 'Description__c',
    SHIPMENT_TYPE: 'Shipment_Type__c',
    TYPE: 'Type__c',
  },
  RETURN_ORDER_LINE_ITEM_CUSTOM: {
    ID: 'Id',
    RETURN_ORDER: 'Order__c',
    PRODUCT: 'Product__c',
    PRODUCT_TOTAL_AMOUNT: 'Product_Total_Amount__c',
    QUANTITY: 'Quantity__c',
    GOOD_QUANTITY: 'Good_Quantity__c',
    DEFECTIVE_QUANTITY: 'Defective_product_Quantity__c',
    STATUS: 'Status__c',
    ORDER_TYPE: 'Order_Type__c',
  },
  INVOICE_CUSTOM: {
    ID: 'Id',
    NAME: 'Name',
    BILLING_ACCOUNT: 'Billing_Account__c',
    ORDER: 'Order__c',
    STATUS: 'Status__c',
    TOTAL_AMOUNT: 'Total_Amount__c',
    INVOICE_DATE: 'Invoice_Date__c',
    DUE_DATE: 'Due_Date__c',
    PAYMENT_STATUS: 'Payment_Status__c',
    CGST: 'CGST__c',
    SGST: 'SGST__c',
    MODE_OF_PAYMENT: 'Mode_Of_Payment__c',
    DISPATCH_REQUEST: 'Dispatch_Request__c',
    TYPE: 'Type__c',
    FULL_PARTIAL: 'Full_Partial__c',
    INVOICE_AMOUNT: 'Invoice_Amount__c',
  },
  INVOICE_LINE_ITEM_CUSTOM: {
    ID: 'Id',
    ORDER_NUMBER: 'Order_Number__c',
    DISCOUNT_AMOUNT: 'Discount_Amount__c',
    DISCOUNT_PERCENTAGE: 'Discount_Percentage__c',
    STATUS: 'Status__c',
    CN_AMOUNT: 'CN_Amount__c',
    CREDIT_NOTE_STATUS: 'credit_note_status__c',
    PROMOTIONS: 'Promotions__c',
  },
  CLAIM_CUSTOM: {
    ID: 'Id',
    NAME: 'Name',
    ACCOUNT: 'Account__c',
    DISTRIBUTOR: 'Distributor__c',
    ORDER: 'Order__c',
    RETURN_ORDER: 'Return_Order__c',
    GRN: 'Goods_Receipt__c',
    PRODUCT: 'FOC_Product__c',
    STATUS: 'Status__c',
    AMOUNT: 'Amount__c',
    TYPE: 'Type__c',
    CLAIM_TYPE: 'Claim_Type__c',
    CLAIM_NUMBER: 'Claim_Number__c',
    TOTAL_AMOUNT: 'Total_Amount__c',
    PURCHASE_RETURN_CLAIM_TYPE: 'Purchase_Return_Claim_Type__c',
    NOTES: 'Notes__c',
    PROMOTION: 'Promotion__c',
    DATE: 'Date__c',
    CURRENCY: 'Currency__c',
  },
  GRN: {
    ID: 'Id',
    NAME: 'Name',
    ACCOUNT: 'Account__c',
    STATUS: 'Status__c',
    AMOUNT: 'Amount__c',
    GRN: 'Goods_Receipt__c',
    NOTES: 'Notes__c',
  },
  DISPATCH_REQUEST: {
    ID: 'Id',
    NAME: 'Dispatch_Request_Name__c',
    ORDER: 'Order__c',
    STATUS: 'Status__c',
    INVOICE: 'Invoice_Custom__c',
    START_DATE: 'Start_Date__c',
    END_DATE: 'End_Date__c',
    SOURCE_ADDRESS: 'Source_Address__c',
    DESTINATION_ADDRESS: 'Destination_Address__c',
  },
  INVENTORY_BATCH: {
    ID: 'Id',
    PRODUCT: 'Product__c',
    DISTRIBUTOR: 'Distributor__c',
    EXPIRY_DATE: 'Expiry_Date__c',
    MANUFACTURE_DATE: 'Manufacture_Date__c',
    STATUS: 'Status__c',
  },
  STORE_SCHEME: {
    ID: 'Id',
    RETAIL_STORE: 'Retail_Store__c',
    STATUS: 'Status__c',
    START_DATE: 'Start_Date__c',
    END_DATE: 'End_Date__c',
    PARTICIPATION_RATE: 'Participation_Rate__c',
  },
  SCHEME_SLAB_TARGET: {
    ID: 'Id',
    PROMOTION: 'Promotion__c',
    DISCOUNT_TYPE: 'Discount_Type__c',
    QUANTITY: 'Quantity__c',
    SLAB_NUMBER: 'Slab_Number__c',
    DISCOUNT: 'Discount__c',
    BUY_VALUE_FROM: 'Buy_Value_From__c',
    BUY_VALUE_TO: 'Buy_Value_To__c',
    FLAT_AMOUNT: 'Flat_Amount__c',
    FREE_QTY: 'Free_Qty__c',
    PRODUCT: 'Product__c',
    PRODUCT_CODE: 'Product_Code__c',
    PRODUCT_NAME: 'Product_name__c',
    PRODUCT_UNIT_PRICE: 'product_unit_price__c',
    CN_AMOUNT: 'CN_Amount__c',
    PAYOUT_PER_QTY: 'Payout_per_Qty__c',
    MIN_QUANTITY: 'Min_Quantity__c',
    MAX_QUANTITY: 'Max_Quantity__c',
    PROMOTIONS: 'Promotions__c',
  },
  PRODUCT: {
    ID: 'Id',
    NAME: 'Name',
    PRODUCT_CODE: 'ProductCode',
    FAMILY: 'Family',
    DESCRIPTION: 'Description',
    IS_ACTIVE: 'IsActive',
    UNIT_OF_MEASURE: 'Unit_Of_Measure__c',
    UNIT_PRICE: 'Unit_Price__c',
    COGS: 'COGS__c',
    BRAND_NAME: 'Brand_Name__c',
    CATEGORY: 'Category__c',
    PRODUCT_CATEGORY: 'Product_Category__c',
    MIN_ORDER_QTY_PRIMARY: 'Minimum_Order_Quantity_Primary__c',
    MIN_ORDER_QTY_SECONDARY: 'Minimum_Order_Quantity_Secondary__c',
    PRIORITY_SKU: 'Priority_SKU__c',
    HIGH_MARGIN_SKU: 'High_Margin_SKU__c',
    PRICE_CHANGED_SKU: 'Price_Changed_SKU__c',
    SCHEME_SKU: 'Scheme_SKU__c',
    PACK_SIZE: 'Pack_Size__c',
    CONTAINER_SIZE: 'Container_Size__c',
    IMAGE_URL: 'ImageUrl__c',
  },
} as const;

export type SalesforceObject =
  (typeof SALESFORCE_OBJECTS)[keyof typeof SALESFORCE_OBJECTS];
export type SalesforceCustomObject =
  (typeof SALESFORCE_CUSTOM_OBJECTS)[keyof typeof SALESFORCE_CUSTOM_OBJECTS];
